controller_joint_names: ['', 'dunno2_left_joint', 'left_wheel_joint', 'dunno2_right_joint', 'right_wheel_joint', 'part3_left_joint', 'left_caster_wheel_joint', 'part3_right_joint', 'right_caster_wheel_joint', ]
